# Generated by Django 3.1.6 on 2021-02-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210214_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicUser',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-registered_at'], 'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
